



export const LOAD_QUIZ_LIST = "LOAD_QUIZ_LIST"
export const LOAD_QUIZ_RESPONSE = "LOAD_QUIZ_RESPONSE"
export const LOAD_WEEK_QUIZ_LIST = "LOAD_WEEK_QUIZ_LIST"
export const LOAD_WEEK_QUIZ_RESPONSE = "LOAD_WEEK_QUIZ_RESPONSE"
export const UPDATE_TOTAL_QUIZ_CORRECT= "UPDATE_TOTAL_QUIZ_CORRECT"
export const UPDATE_TOTAL_QUIZ_INCORRECT= "UPDATE_TOTAL_QUIZ_INCORRECT"
export const UPDATE_TOTAL_QUIZ_PERCENT= "UPDATE_TOTAL_QUIZ_PERCENT"
export const UPDATE_TOTAL_QUIZ_COUNT= "UPDATE_TOTAL_QUIZ_COUNT"
export const LOAD_USER_PROFILE= "LOAD_USER_PROFILE"
export const UPDATE_USER_PROFILE= "UPDATE_USER_PROFILE"

